name: PlasmaCore
version: 1.0.0
main: com.plasma.core.PlasmaCore
api-version: '1.20'
description: Социальная платформа PLASMA MC
author: PLASMA

commands:
  plasma:
    description: Главная команда
    usage: /plasma
  
  apply:
    description: Подать заявку
    usage: /apply <telegram|discord> <username>
  
  balance:
    description: Баланс монет
    usage: /balance
    aliases: [bal, money]
  
  pay:
    description: Перевод монет
    usage: /pay <игрок> <сумма>
  
  project:
    description: Управление проектами
    usage: /project
    aliases: [proj, p]
  
  shop:
    description: Управление лавкой
    usage: /shop
  
  gallery:
    description: Галерея
    usage: /gallery
    aliases: [gal]
  
  memory:
    description: Стена памяти
    usage: /memory
  
  vote:
    description: Голосования
    usage: /vote
  
  contest:
    description: Конкурсы
    usage: /contest
  
  delegate:
    description: Делегации
    usage: /delegate
    aliases: [del]
  
  like:
    description: Лайк
    usage: /like <проект>
  
  spawn:
    description: Вернуться
    usage: /spawn

permissions:
  plasma.owner:
    description: Владелец сервера
    default: op
  
  plasma.player:
    description: Игрок
    default: true
